Pin dkml-workflows to 1.0.1-r1 (3/n)

diff --git a/ci/setup-dkml/gh-windows/action.yml b/ci/setup-dkml/gh-windows/action.yml
--- a/ci/setup-dkml/gh-windows/action.yml
+++ b/ci/setup-dkml/gh-windows/action.yml
@@ -47,7 +47,11 @@ inputs:
   VERBOSE:
     description: "Turn on verbose logging"
     required: false
-    default: 'true'
+    default: 'false'
+  SECONDARY_SWITCH:
+    description: "Turn on secondary 'two' switch"
+    required: false
+    default: 'false'
 
 runs:
   using: "composite"
@@ -380,6 +384,7 @@ runs:
         DKML_COMPILER=${DKML_COMPILER:-}
         OCAML_COMPILER=${OCAML_COMPILER:-}
         CONF_DKML_CROSS_TOOLCHAIN=${CONF_DKML_CROSS_TOOLCHAIN:-}
+        SECONDARY_SWITCH=${SECONDARY_SWITCH:-}
         VERBOSE=${VERBOSE:-}
         .
         -------------------
@@ -697,6 +702,13 @@ runs:
         if [ "${PATCH_OS_DISTRIBUTION_WIN32}" = true ]; then export OPAMVAR_os_distribution=win32; fi
         if [ "${PATCH_EXE_WIN32}" = true ]; then export OPAMVAR_exe=.exe; fi
         
+        # Reset environment so no conflicts with a parent Opam or OCaml system
+        unset OPAM_SWITCH_PREFIX
+        unset OPAMSWITCH
+        unset CAML_LD_LIBRARY_PATH
+        unset OCAMLLIB
+        unset OCAML_TOPLEVEL_PATH
+        
         echo "Running inside Docker container: \$*" >&2
         set +e
         "\$@"
@@ -777,6 +789,13 @@ runs:
         export OPAMROOTISOK=1
         if [ "${PATCH_OS_DISTRIBUTION_WIN32}" = true ]; then export OPAMVAR_os_distribution=win32; fi
         if [ "${PATCH_EXE_WIN32}" = true ]; then export OPAMVAR_exe=.exe; fi
+        
+        # Reset environment so no conflicts with a parent Opam or OCaml system
+        unset OPAM_SWITCH_PREFIX
+        unset OPAMSWITCH
+        unset CAML_LD_LIBRARY_PATH
+        unset OCAMLLIB
+        unset OCAML_TOPLEVEL_PATH
         
         echo "Running: \$*" >&2
         set +e
@@ -926,40 +945,58 @@ runs:
         opamrun update default diskuv
         section_end opam-repo
         
-        section_begin switch-create "Create Opam switch"
-        # Create, or recreate, the Opam switch. The Opam switch should not be
-        # cached except for the compiler (confer docs for setup-ocaml GitHub
-        # Action) which is the 'dkml' switch
-        # Check if the switch name is present in the Opam root (which may come from cache)
-        NOMINALLY_PRESENT=false
-        if opamrun switch list --short | grep '^dkml$'; then NOMINALLY_PRESENT=true; fi
+        do_switch_create() {
+            do_switch_create_NAME=$1
+            shift
         
-        # Check if the switch is actually present in case of cache incoherence
-        # or corrupt Opam state that could result in:
-        #   Error:  No config file found for switch dkml. Switch broken?
-        if [ $NOMINALLY_PRESENT = true ] && [ ! -e "$opam_root/dkml/.opam-switch/switch-config" ]; then
-            # Remove the switch name from Opam root, and any partial switch state.
-            # Ignore inevitable warnings/failure about missing switch.
-            opamrun switch remove dkml --yes || true
-            rm -rf "$opam_root/dkml"
+            section_begin "switch-create-$do_switch_create_NAME" "Create Opam switch $do_switch_create_NAME"
+            # Create, or recreate, the Opam switch. The Opam switch should not be
+            # cached except for the compiler (confer docs for setup-ocaml GitHub
+            # Action) which is the 'dkml' switch (or the 'two' switch).
+            # Check if the switch name is present in the Opam root (which may come from cache)
             NOMINALLY_PRESENT=false
-        fi
+            if opamrun switch list --short | grep "^${do_switch_create_NAME}\$"; then NOMINALLY_PRESENT=true; fi
         
-        if [ $NOMINALLY_PRESENT = false ]; then
-            opamrun switch create dkml --repos diskuv,default --empty --yes
+            # Check if the switch is actually present in case of cache incoherence
+            # or corrupt Opam state that could result in:
+            #   Error:  No config file found for switch dkml. Switch broken?
+            if [ $NOMINALLY_PRESENT = true ] && [ ! -e "$opam_root/$do_switch_create_NAME/.opam-switch/switch-config" ]; then
+                # Remove the switch name from Opam root, and any partial switch state.
+                # Ignore inevitable warnings/failure about missing switch.
+                opamrun switch remove "$do_switch_create_NAME" --yes || true
+                rm -rf "${opam_root:?}/$do_switch_create_NAME"
+                NOMINALLY_PRESENT=false
+            fi
+        
+            if [ $NOMINALLY_PRESENT = false ]; then
+                opamrun switch create "$do_switch_create_NAME" --repos diskuv,default --empty --yes
+            fi
+            section_end "switch-create-$do_switch_create_NAME"
+        }
+        do_switch_create dkml
+        if [ "${SECONDARY_SWITCH:-}" = "true" ]; then
+            do_switch_create two
+        else
+            # Always create a secondary switch ... just empty. Avoid problems with cache content missing
+            # and idempotency.
+            opamrun switch remove two --yes || true
+            rm -rf "$opam_root/two"
+            opamrun switch create two --empty --yes
         fi
-        section_end switch-create
         
         do_pins() {
+            do_pins_NAME=$1
+            shift
+        
             # dkml-base-compiler
         
             if [ "${DKML_COMPILER:-}" != '@repository@' ] && [ -z "${DKML_COMPILER:-}" ] && [ -z "${OCAML_COMPILER:-}" ]; then
-                section_begin checkout-dkml-base-compiler "Pin dkml-base-compiler to default ${DEFAULT_DKML_COMPILER} (neither dkml-base-compiler nor OCAML_COMPILER specified)"
-                opamrun pin add --yes --no-action dkml-base-compiler "https://github.com/diskuv/dkml-compiler.git#${DEFAULT_DKML_COMPILER}"
+                section_begin checkout-dkml-base-compiler "Pin dkml-base-compiler to default ${DEFAULT_DKML_COMPILER} (neither dkml-base-compiler nor OCAML_COMPILER specified) for $do_pins_NAME switch"
+                opamrun pin add --switch "$do_pins_NAME" --yes --no-action dkml-base-compiler "https://github.com/diskuv/dkml-compiler.git#${DEFAULT_DKML_COMPILER}"
                 section_end checkout-dkml-base-compiler
             elif [ "${DKML_COMPILER:-}" != '@repository@' ] && [ -n "${DKML_COMPILER:-}" ] && [ -z "${OCAML_COMPILER:-}" ]; then
-                section_begin checkout-dkml-base-compiler "Pin dkml-base-compiler to $DKML_COMPILER (dkml-base-compiler specified; no OCAML_COMPILER specified)"
-                opamrun pin add --yes --no-action dkml-base-compiler "https://github.com/diskuv/dkml-compiler.git#${DKML_COMPILER}"
+                section_begin checkout-dkml-base-compiler "Pin dkml-base-compiler to $DKML_COMPILER (dkml-base-compiler specified; no OCAML_COMPILER specified) for $do_pins_NAME switch"
+                opamrun pin add --switch "$do_pins_NAME" --yes --no-action dkml-base-compiler "https://github.com/diskuv/dkml-compiler.git#${DKML_COMPILER}"
                 section_end checkout-dkml-base-compiler
             elif [ -n "${OCAML_COMPILER:-}" ]; then
                 # Validate OCAML_COMPILER (OCAML_COMPILER specified)
@@ -971,16 +1008,16 @@ runs:
                     ;;
                 esac
         
-                section_begin checkoutdkml-base-compiler 'Pin dkml-base-compiler (OCAML_COMPILER specified)'
-                opamrun pin add --yes --no-action dkml-base-compiler "https://github.com/diskuv/dkml-compiler.git#${OCAML_COMPILER}-v${DKML_VERSION}"
+                section_begin checkout-dkml-base-compiler "Pin dkml-base-compiler (OCAML_COMPILER specified) for $do_pins_NAME switch"
+                opamrun pin add --switch "$do_pins_NAME" --yes --no-action dkml-base-compiler "https://github.com/diskuv/dkml-compiler.git#${OCAML_COMPILER}-v${DKML_VERSION}"
                 section_end checkout-dkml-base-compiler
             fi
         
             # conf-dkml-cross-toolchain
         
             if [ "${CONF_DKML_CROSS_TOOLCHAIN:-}" != '@repository@' ]; then
-                section_begin checkout-conf-dkml-cross-toolchain 'Pin conf-dkml-cross-toolchain'
-                opamrun pin add --yes --no-action conf-dkml-cross-toolchain "https://github.com/diskuv/conf-dkml-cross-toolchain.git#$CONF_DKML_CROSS_TOOLCHAIN"
+                section_begin checkout-conf-dkml-cross-toolchain "Pin conf-dkml-cross-toolchain for $do_pins_NAME switch"
+                opamrun pin add --switch "$do_pins_NAME" --yes --no-action conf-dkml-cross-toolchain "https://github.com/diskuv/conf-dkml-cross-toolchain.git#$CONF_DKML_CROSS_TOOLCHAIN"
                 section_end checkout-conf-dkml-cross-toolchain
             fi
         
@@ -1014,31 +1051,36 @@ runs:
             #
             # - ppx_expect; only patch is for v0.14.1. Need to upstream fix the problem.
             # - base; patches for v0.14.1/2/3. Need to upstream fix the problem.
-            opamrun pin add --yes --no-action -k version base "${PIN_BASE}"
-            opamrun pin add --yes --no-action -k version bigstringaf "${PIN_BIGSTRINGAF}"
-            opamrun pin add --yes --no-action -k version core_kernel "${PIN_CORE_KERNEL}"
-            opamrun pin add --yes --no-action -k version ctypes "${PIN_CTYPES}"
-            opamrun pin add --yes --no-action -k version ctypes-foreign "${PIN_CTYPES_FOREIGN}"
-            opamrun pin add --yes --no-action -k version curly "${PIN_CURLY}"
-            opamrun pin add --yes --no-action -k version digestif "${PIN_DIGESTIF}"
-            opamrun pin add --yes --no-action -k version dune "${PIN_DUNE}"
-            opamrun pin add --yes --no-action -k version dune-configurator "${PIN_DUNE}"
-            opamrun pin add --yes --no-action -k version ocamlbuild "${PIN_OCAMLBUILD}"
-            opamrun pin add --yes --no-action -k version ocamlfind "${PIN_OCAMLFIND}"
-            opamrun pin add --yes --no-action -k version ocp-indent "${PIN_OCP_INDENT}"
-            opamrun pin add --yes --no-action -k version ppx_expect "${PIN_PPX_EXPECT}"
-            opamrun pin add --yes --no-action -k version ptime "${PIN_PTIME}"
-            opamrun pin add --yes --no-action -k version time_now "${PIN_TIME_NOW}"
+            section_begin "opam-pins-$do_pins_NAME" "Opam pins for $do_pins_NAME switch"
+            opamrun pin add --switch "$do_pins_NAME"  --yes --no-action -k version base "${PIN_BASE}"
+            opamrun pin add --switch "$do_pins_NAME"  --yes --no-action -k version bigstringaf "${PIN_BIGSTRINGAF}"
+            opamrun pin add --switch "$do_pins_NAME"  --yes --no-action -k version core_kernel "${PIN_CORE_KERNEL}"
+            opamrun pin add --switch "$do_pins_NAME"  --yes --no-action -k version ctypes "${PIN_CTYPES}"
+            opamrun pin add --switch "$do_pins_NAME"  --yes --no-action -k version ctypes-foreign "${PIN_CTYPES_FOREIGN}"
+            opamrun pin add --switch "$do_pins_NAME"  --yes --no-action -k version curly "${PIN_CURLY}"
+            opamrun pin add --switch "$do_pins_NAME"  --yes --no-action -k version digestif "${PIN_DIGESTIF}"
+            opamrun pin add --switch "$do_pins_NAME"  --yes --no-action -k version dune "${PIN_DUNE}"
+            opamrun pin add --switch "$do_pins_NAME"  --yes --no-action -k version dune-configurator "${PIN_DUNE}"
+            opamrun pin add --switch "$do_pins_NAME"  --yes --no-action -k version ocamlbuild "${PIN_OCAMLBUILD}"
+            opamrun pin add --switch "$do_pins_NAME"  --yes --no-action -k version ocamlfind "${PIN_OCAMLFIND}"
+            opamrun pin add --switch "$do_pins_NAME"  --yes --no-action -k version ocp-indent "${PIN_OCP_INDENT}"
+            opamrun pin add --switch "$do_pins_NAME"  --yes --no-action -k version ppx_expect "${PIN_PPX_EXPECT}"
+            opamrun pin add --switch "$do_pins_NAME"  --yes --no-action -k version ptime "${PIN_PTIME}"
+            opamrun pin add --switch "$do_pins_NAME"  --yes --no-action -k version time_now "${PIN_TIME_NOW}"
+            section_end "opam-pins-$do_pins_NAME"
         }
         
-        section_begin opam-pins 'Opam pins'
-        do_pins
-        section_end opam-pins
+        do_pins dkml
+        if [ "${SECONDARY_SWITCH:-}" = "true" ]; then
+            do_pins two
+        fi
         
         do_use_vsstudio() {
+            do_use_vsstudio_NAME=$1
+            shift
             case "$dkml_host_abi" in
             windows_*)
-                section_begin use-vsstudio 'Use Visual Studio in dkml-* Opam packages (Windows)'
+                section_begin "use-vsstudio-$do_use_vsstudio_NAME" "Use Visual Studio in dkml-* Opam packages (Windows) for $do_use_vsstudio_NAME switch"
         
                 # shellcheck disable=SC2153
                 E_VS_DIR=$(escape_arg_as_ocaml_string "$VS_DIR")
@@ -1057,7 +1099,7 @@ runs:
                         echo Opam 2.0 support in dockcross to use a portable opam var prefix not yet implemented
                         exit 67
                     fi
-                    OP=$(opamrun var prefix)
+                    OP=$(opamrun var prefix --switch "$do_use_vsstudio_NAME")
                     OPSC=$OP/.opam-switch/switch-config
                     if grep setenv: "$OPSC"; then
                         echo "INFO: Updating switch-config. Old was:"
@@ -1079,44 +1121,58 @@ runs:
                     cat "$OPSC" >&2 # print
                     ;;
                 *)
-                    opamrun option setenv= # reset
-                    opamrun option setenv+='DKML_COMPILE_SPEC = "1"'
-                    opamrun option setenv+='DKML_COMPILE_TYPE = "VS"'
-                    opamrun option setenv+="DKML_COMPILE_VS_DIR = \"$E_VS_DIR\""
-                    opamrun option setenv+="DKML_COMPILE_VS_VCVARSVER = \"$E_VS_VCVARSVER\""
-                    opamrun option setenv+="DKML_COMPILE_VS_WINSDKVER = \"$E_VS_WINSDKVER\""
-                    opamrun option setenv+="DKML_COMPILE_VS_MSVSPREFERENCE = \"$E_VS_MSVSPREFERENCE\""
-                    opamrun option setenv+="DKML_COMPILE_VS_CMAKEGENERATOR = \"$E_VS_CMAKEGENERATOR\""
-                    opamrun option setenv+="DKML_HOST_ABI = \"${dkml_host_abi}\""
-                    opamrun option setenv # print
+                    opamrun option --switch "$do_use_vsstudio_NAME" setenv= # reset
+                    opamrun option --switch "$do_use_vsstudio_NAME" setenv+='DKML_COMPILE_SPEC = "1"'
+                    opamrun option --switch "$do_use_vsstudio_NAME" setenv+='DKML_COMPILE_TYPE = "VS"'
+                    opamrun option --switch "$do_use_vsstudio_NAME" setenv+="DKML_COMPILE_VS_DIR = \"$E_VS_DIR\""
+                    opamrun option --switch "$do_use_vsstudio_NAME" setenv+="DKML_COMPILE_VS_VCVARSVER = \"$E_VS_VCVARSVER\""
+                    opamrun option --switch "$do_use_vsstudio_NAME" setenv+="DKML_COMPILE_VS_WINSDKVER = \"$E_VS_WINSDKVER\""
+                    opamrun option --switch "$do_use_vsstudio_NAME" setenv+="DKML_COMPILE_VS_MSVSPREFERENCE = \"$E_VS_MSVSPREFERENCE\""
+                    opamrun option --switch "$do_use_vsstudio_NAME" setenv+="DKML_COMPILE_VS_CMAKEGENERATOR = \"$E_VS_CMAKEGENERATOR\""
+                    opamrun option --switch "$do_use_vsstudio_NAME" setenv+="DKML_HOST_ABI = \"${dkml_host_abi}\""
+                    opamrun option --switch "$do_use_vsstudio_NAME" setenv # print
                     ;;
                 esac
         
                 # shellcheck disable=SC2016
-                opamrun exec -- sh -c 'echo $VCToolsRedistDir'
+                opamrun exec --switch "$do_use_vsstudio_NAME" -- sh -c 'echo $VCToolsRedistDir'
         
-                section_end use-vsstudio
+                section_end "use-vsstudio-$do_use_vsstudio_NAME"
                 ;;
             esac
         }
-        do_use_vsstudio
+        #   Make 'two' first so that 'dkml' is the final active switch.
+        if [ "${SECONDARY_SWITCH:-}" = "true" ]; then
+            do_use_vsstudio two
+        fi
+        do_use_vsstudio dkml
         
         do_install_compiler() {
-            section_begin install-compiler "Install OCaml compiler"
-            opamrun pin list
+            do_install_compiler_NAME=$1
+            shift
+            section_begin "install-compiler-$do_install_compiler_NAME" "Install OCaml compiler for $do_install_compiler_NAME switch"
+            opamrun pin list --switch "$do_install_compiler_NAME"
             # shellcheck disable=SC2086
-            opamrun upgrade --yes dkml-base-compiler conf-dkml-cross-toolchain ${ocaml_options:-}
-            section_end install-compiler
+            opamrun upgrade --switch "$do_install_compiler_NAME" --yes dkml-base-compiler conf-dkml-cross-toolchain ${ocaml_options:-}
+            section_end "install-compiler-$do_install_compiler_NAME"
         }
-        do_install_compiler
+        do_install_compiler dkml
+        if [ "${SECONDARY_SWITCH:-}" = "true" ]; then
+            do_install_compiler two
+        fi
         
         do_summary() {
-            section_begin summary "Summary"
-            opamrun var
-            opamrun exec -- ocamlc -config
-            section_end summary
+            do_summary_NAME=$1
+            shift
+            section_begin "summary-$do_summary_NAME" "Summary for $do_summary_NAME switch"
+            opamrun var --switch "$do_summary_NAME"
+            opamrun exec --switch "$do_summary_NAME" -- ocamlc -config
+            section_end "summary-$do_summary_NAME"
         }
-        do_summary
+        do_summary dkml
+        if [ "${SECONDARY_SWITCH:-}" = "true" ]; then
+            do_summary two
+        fi
         
         end_of_script
 
@@ -1251,7 +1307,7 @@ runs:
       shell: bash
       run: |
         set -x
-        echo '1-507384-${{ inputs.FDOPEN_OPAMEXE_BOOTSTRAP }}-${{ steps.full_matrix_vars.outputs.dkml_host_abi }}-${{ steps.full_matrix_vars.outputs.opam_abi }}-${{ steps.full_matrix_vars.outputs.bootstrap_opam_version }}' > .ci/sd4/cachekey.opam.binaries
+        echo '1-52d559-${{ inputs.FDOPEN_OPAMEXE_BOOTSTRAP }}-${{ steps.full_matrix_vars.outputs.dkml_host_abi }}-${{ steps.full_matrix_vars.outputs.opam_abi }}-${{ steps.full_matrix_vars.outputs.bootstrap_opam_version }}' > .ci/sd4/cachekey.opam.binaries
         echo '1-${{ steps.full_matrix_vars.outputs.abi_pattern }}-${{ steps.full_matrix_vars.outputs.vsstudio_arch }}-${{ steps.full_matrix_vars.outputs.vsstudio_hostarch }}-${{ steps.full_matrix_vars.outputs.vsstudio_dir }}-${{ steps.full_matrix_vars.outputs.vsstudio_vcvarsver }}-${{ steps.full_matrix_vars.outputs.vsstudio_winsdkver }}-${{ steps.full_matrix_vars.outputs.vsstudio_msvspreference }}-${{ steps.full_matrix_vars.outputs.vsstudio_cmakegenerator }}' > .ci/sd4/cachekey.vsstudio
         echo '1-${{ inputs.OCAML_COMPILER }}-${{ inputs.DISKUV_OPAM_REPOSITORY }}-${{ inputs.DKML_COMPILER }}-${{ inputs.CONF_DKML_CROSS_TOOLCHAIN }}' > .ci/sd4/cachekey.ci.inputs
 
@@ -1272,6 +1328,7 @@ runs:
         path: |
           ${{ steps.full_matrix_vars.outputs.opam_root }}/config
           ${{ steps.full_matrix_vars.outputs.opam_root }}/dkml
+          ${{ steps.full_matrix_vars.outputs.opam_root }}/two
           ${{ steps.full_matrix_vars.outputs.opam_root }}/repo
           ${{ steps.full_matrix_vars.outputs.opam_root }}/download-cache
           ${{ steps.full_matrix_vars.outputs.opam_root }}/.ci.root-init
@@ -1344,6 +1401,7 @@ runs:
         DISKUV_OPAM_REPOSITORY:           "${{ inputs.DISKUV_OPAM_REPOSITORY }}"
         DKML_COMPILER:                    "${{ inputs.DKML_COMPILER }}"
         OCAML_COMPILER:                   "${{ inputs.OCAML_COMPILER }}"
+        SECONDARY_SWITCH:                 "${{ inputs.SECONDARY_SWITCH }}"
         VERBOSE:                          "${{ inputs.VERBOSE }}"
 
         # autogen from global_env_vars.
